site_name: bstats
site_url: https://phisherman.readthedocs.io

repo_url: https://github.com/Bimi05/bstats
repo_name: Bimi05/bstats

theme:
  palette:
    - scheme: default
      toggle:
        icon: material/lightbulb
        name: Switch to dark mode
    - scheme: slate
      toggle:
        icon: material/lightbulb-outline
        name: Switch to light mode
  icon:
    repo: fontawesome/brands/github
  name: "material"

nav:
  - Home: index.md
  - Code Reference: code-reference.md

plugins:
  - search
  - mkdocstrings
